version: "3"

services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest
    restart: unless-stopped
    depends_on:
      - piped
    container_name: piped-frontend
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/BACKEND_HOSTNAME/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'

  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    restart: unless-stopped
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket
    container_name: piped-proxy

  piped:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config/config.properties:/app/config.properties:ro
    depends_on:
      - postgres
    container_name: piped-backend

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_DATA_DIR}/data/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${APP_DATA_DIR}/data/config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
      - ${APP_DATA_DIR}/data/config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
      - ${APP_DATA_DIR}/data/config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
      - ${APP_DATA_DIR}/data/config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
      - piped-proxy:/var/run/ytproxy
    container_name: nginx
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=changeme
    container_name: postgres

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    container_name: watchtower
    command: piped-frontend piped-backend piped-proxy varnish nginx postgres watchtower

volumes:
  piped-proxy: null
